language: node_js
node_js:
  - "8"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test && npm run build
after_success:
  - cd lib
  - cp ../yarn.lock .
  - yarn install --production
